import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import ToastProvider from "@/components/ToastProvider";
import Providers from "@/redux/provider";
import QueryProvider from "@/react-query/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog app in NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ToastProvider>
            <Navigation />
            <main className="max-w-5xl mx-auto">
              <QueryProvider>{children}</QueryProvider>
            </main>
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
